In [2]:
'''1. Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program to
compute the mean and variance of the elements present in the array.'''

import numpy as np
vector = np.array([11, 12, 13, 14, 15])
mean = np.mean(vector)
variance = np.var(vector, ddof=1)
print("Mean: ", mean)
print("Variance: ", variance)


Mean:  13.0
Variance:  2.5


In [7]:
'''2.Create two vectors each of dimension 1XM each representing N-
dimensional feature vector of a sample. Write a program to compute the Covariance between them.'''

import numpy as np
array1 = np.array([11, 12, 13, 14, 15])
array2 = np.array([22, 23, 24, 25, 26])
covariance_result = np.cov(array1, array2, ddof=1)[0][1]
print("Covariance: ", covariance_result)


Covariance:  2.5


In [9]:
'''3.Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.'''

import numpy as np
data_array1 = np.array([11, 12, 13, 14, 15])
data_array2 = np.array([22, 23, 24, 25, 26])
correlation_coefficient = np.corrcoef(data_array1, data_array2)[0][1]
print("Correlation: ", correlation_coefficient)


Correlation:  0.9999999999999999


In [10]:
'''Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th entry 
of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and correlation matrix. 
Comment on takeaways from these matrixes.'''

import numpy as np
matrix = np.array([[10,11,12], [17,18,19], [26,27,28]])
covariance_matrix = np.cov(matrix, rowvar=False)
correlation_matrix = np.corrcoef(matrix, rowvar=False)
print("Covariance matrix:")
print(covariance_matrix)
print("Correlation matrix:")
print(correlation_matrix)


Covariance matrix:
[[64.33333333 64.33333333 64.33333333]
 [64.33333333 64.33333333 64.33333333]
 [64.33333333 64.33333333 64.33333333]]
Correlation matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
